### ISSUE TITLE
com.imobicloud.accordion Example

### ISSUE THREAD

**Issue by ndgwv** [imobicloud/ui#8]
Could you please provide an example of the com.imobicloud.accordion widget (xml sample would be very helpful)

**Comment by imobicloud** [comment]
This widget is out of update, please use with caution :)
xml example here

<Widget src="com.imobicloud.accordion">
    <View role="header"><Label>Header 1</Label></View>
    <View role="body"><Label>Body 1</Label></View>
    <View role="header"><Label>Header 2</Label></View>
    <View role="body"><Label>Body 3</Label></View>
</Widget>
